### ISSUE TITLE
More sym solver stuff

### ISSUE THREAD

**Issue by jgraley** [jgraley/inferno-cpp2v#507]
### More derivation
 - [x] Derive direct implications (i.e > implies >= etc)
 - [x] Derive contradictions
 - <strike>Re-run derivation/extension until no more found</strike>

### More solvability
 - [x] Category-results - need eval kit or just The Knowledge to work
 - [x] Inequalities solve to category-result on depth-first ordering
 - [x] Equivalence solves to category-result on simple compare ordering (discovered need for #525 doing this)
 - [x] Solve the AllDiff, presumably directly into a set result with complement flag set
 - [x] #528
 - <strike>Solver for `GreenGrassAgent::IsGreenGrassOperator`</strike>

### Simplification etc
 - [x] Eliminate "ToEqual" on solvers for bool/pred expressions. 
   - Assume `true` and when solving `NotOperator` just insert `ComplementOperator`.
   - See #527
 - [x] `Is` on the front of predicates; 
   - c.f. `All` on the front of the corresponding set operators.
 - <strike>Rethink precedence scheme
   - For set operators that look like eg `{<something}`. 
   - Need separate _inner_ and _outer_ precedences. 
   - In example, inner is `COMPARE` and outer is `SCOPE` or thereabouts.</strike>
 - [x] Tidy `TrySolveForToEqualNT()` on the pred operators 
   - They seem to duplicate some stuff and are confusing. Can we do better?
   - <strike>If `TrySolveForToEqual()` rarely depends on the ToEqual arg for success/fail, then a `CanSolveFor()` could be created, and we could use this to orient the solve without needing to prepare the ToEqual expression first, avoiding ugly discarded computations.</strike> too much churn
### TODOs
 - <strike>The `ASSERTFAIL("TODO");`s in `result.cpp`</strike>Moving to #514

**Comment by jgraley** [comment]
Redacted some ideas here to keep changes simple (not increasing non-comment LOCs)

**Comment by jgraley** [comment]
Done enough for milestone
